---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib
  labels:
    app.kubernetes.io/name: fib
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: fib
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fib
    spec:
      containers:
        - name: fib
          image: localhost:5001/cache-client:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: groupcache
          env:
            - name: SERVICE_NAME
              value: fib
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SELF
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GROUPCACHE_PORT
              value: "8081"
            - name: HTTP_PORT
              value: "8080"
      serviceAccount: fib
---
apiVersion: v1
kind: Service
metadata:
  name: fib
spec:
  selector:
    app.kubernetes.io/name: fib
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: groupcache
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fib
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fib
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fib
subjects:
  - kind: ServiceAccount
    name: fib
roleRef:
  kind: Role
  name: fib
  apiGroup: rbac.authorization.k8s.io
